; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env]
monitor_speed = 115200
upload_speed = 921600
;platform = espressif32
;platform = https://github.com/Jason2866/platform-espressif32.git#Arduino/IDF5
platform = https://github.com/platformio/platform-espressif32.git # development version
framework = arduino
; https://registry.platformio.org/tools/espressif/toolchain-riscv32-esp/versions
;platform_packages = espressif/toolchain-riscv32-esp
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
monitor_filters = esp32_exception_decoder

lib_deps = 
    https://github.com/h2zero/NimBLE-Arduino@^2.3.0
    https://github.com/bblanchon/ArduinoJson.git


#####################################################################
[env:firmware_ESP32-Flowercare]
board = esp32dev
;board_build.partitions = min_spiffs.csv
lib_deps = ${env.lib_deps}

