name: Build_Manifest
on:
  push:
    branches:
      - web-installer
    paths:
      - '**.yml'
      - '**.sh'

jobs:
    
  build:
    name: Build_Manifest
    runs-on: ubuntu-latest
    env:
      REPOSITORY: ${{ github.event.repository.name }}
            
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip


      - name: Display generated files
        run: |
          ls -R ${{ github.workspace }}/

