# https://github.com/marketplace/actions/test-compile-for-arduino
# https://github.com/marketplace/actions/test-compile-for-arduino#multiple-boards-with-parameter-using-the-script-directly
# https://github.com/actions/upload-release-asset/issues/17
# https://github.com/dh1tw/remoteAudio/blob/master/.github/workflows/build.yml 

name: Build&Deploy
on:
  push:
    branches:
      - master
      - prelive
      - development
    paths:
      - '**.cpp'
      - '**.h'
      - '**.yml'
      - '**.sh'

jobs:
    
  build:
    name: BuildAndDeploy-${{ matrix.variant }}
    runs-on: ubuntu-latest
    env:
      REPOSITORY: ${{ github.event.repository.name }}

    outputs:
      fw_version: ${{ steps.json_params.outputs.version }}
      fw_subversion: ${{ steps.json_params.outputs.subversion }}
      fw_stage: ${{ steps.json_params.outputs.stage }}

    strategy:
      matrix:
        variant:
          - firmware_ESP32
          - firmware_ESP32-S2
          - firmware_ESP32-S3
          - firmware_ESP32-C3
#          - firmware_ESP32_WebSerial 

        include:
          - variant: firmware_ESP32
            architecture: ESP32
          - variant: firmware_ESP32-S2
            architecture: ESP32-S2
          - variant: firmware_ESP32-S3
            architecture: ESP32-S3
          - variant: firmware_ESP32-C3
            architecture: ESP32-C3
#          - variant: firmware_ESP32_WebSerial
#            architecture: ESP32_dbg
            
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -U platformio
          pip install -U esptool

      - name: Run PlatformIO
        run: |
          platformio run -e ${{ matrix.variant }}
          platformio run --target buildfs -e ${{ matrix.variant }}

      - name: Build merged Firmware
        run: |
          esptool.py --chip ${{ matrix.architecture }} merge_bin \
            --output .pio/build/${{ matrix.variant }}/merged-firmware.bin \
            --flash_mode dio \
            --flash_freq 40m \
            --flash_size 4MB \
            0x1000 .pio/build/${{ matrix.variant }}/bootloader.bin \
            0x8000 .pio/build/${{ matrix.variant }}/partitions.bin \
            0x10000 .pio/build/${{ matrix.variant }}/firmware.bin \
            0x350000 .pio/build/${{ matrix.variant }}/littlefs.bin

      - name: Display generated files
        run: |
          ls -R .pio/build/${{ matrix.variant }}/

      - if: endsWith(github.ref, 'master')
        name: Set Environment Variable "PRODUCTION" 
        run: echo "ENV_STAGE=PROD" >> $GITHUB_ENV
      - if: endsWith(github.ref, 'prelive')
        name: Set Environment Variable "PreLive" 
        run: echo "ENV_STAGE=PRE" >> $GITHUB_ENV
      - if: endsWith(github.ref, 'development')
        name: Set Environment Variable "Development" 
        run: echo "ENV_STAGE=DEV" >> $GITHUB_ENV

      # Script um JSON Datei zu erstellen
      - name: Schreibe Json File
        id: json_params 
        env:
          ENV_ARCH: ${{ matrix.architecture }}
          ENV_REPOSITORYNAME: ${{ env.REPOSITORY }}
          ENV_BINARYPATH: .pio/build/${{ matrix.variant }}/
          ENV_RELEASEPATH: "release"
          ENV_ARTIFACTPATH: "artifacts"
          ENV_SUBVERSION: ${{ github.run_number }}
          ENV_RELEASEFILE: include/_Release.h
        run: |
          mkdir -p release artifacts
          chmod +x .github/workflows/generateJSON.sh
          .github/workflows/generateJSON.sh >> "$GITHUB_OUTPUT"

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.variant }}.zip"
          path: artifacts/*
  
      - name: Upload to AWS S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: '--acl public-read --follow-symlinks'
        env:
          AWS_S3_BUCKET: 'tfa-releases'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-central-1'   # optional: defaults to us-east-1
          SOURCE_DIR: 'release'      # optional: defaults to entire repository
          DEST_DIR: ${{ env.REPOSITORY }}     


  web-installer:
    needs: [build]
    runs-on: ubuntu-latest
    env:
      GITHUB_REPOSITORY: ${{ github.event.repository.name }}
      fw_path: "web-installer/firmware/v${{ needs.build.outputs.fw_version }}-${{ needs.build.outputs.fw_subversion }}-${{ needs.build.outputs.fw_stage }}"
      root_path: "app/firmware"

    steps:
      - name: Checkout web-installer Repository
        uses: actions/checkout@v4
        with:
          ref: 'web-installer'
          path: 'web-installer'

      - name: Checkout Application Repository
        uses: actions/checkout@v2
        with:
          path: 'app'
#          sparse-checkout: |
#            .github

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Download all Artifacts 
        uses: actions/download-artifact@v4
        with:
          path: ${{ env.fw_path }}

      - name: Display generated files
        run: |
          ls -laR ./

      - name: Handle Manifest JSON
        run: |
          python -m pip install --upgrade pip
          python app/.github/workflows/createManifest.py --FwDir ${{ env.fw_path }} --RootDir ${{ env.root_path }}


# merged-firmware.ESP32.v2.5.0-192.DEV.bin

#      - name: set Environment Variables
#        id: set_env_var
#        run: |
#          IFS='.' read -r -a array <<< "merged-firmware.ESP32.v2.5.0-192.DEV.bin"

      - name: Display generated files
        run: |
          ls -R ./

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add *
          git commit -m "neue Firmware v${{ needs.build.outputs.fw_version }}-${{ needs.build.outputs.fw_subversion }}-${{ needs.build.outputs.fw_stage }}"
          git push origin web-installer  


  create_Release:
    needs: [build]

    runs-on: ubuntu-latest
    if: endsWith(github.ref, 'master') || endsWith(github.ref, 'prelive')
    
    env:
      GITHUB_REPOSITORY: ${{ github.event.repository.name }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Download all Artifacts 
        uses: actions/download-artifact@main
        with:
          path: ./release

      - name: Display files
        run: |
            ls -R ./release
    
      - name: set Environment Variables
        id: set_env_var
        run: |
                 VERSION=$(sed 's/[^0-9|.]//g' include/_Release.h)  # zb. 2.4.2 
                 if [ ${{ github.ref }} == 'refs/heads/master' ]; then IS_PRE='false'; else IS_PRE='true'; fi
                 if [ ${{ github.ref }} == 'refs/heads/master' ]; then POSTFIX=''    ; else POSTFIX='PRE'; fi
                 echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
                 echo "IS_PRERELEASE=${IS_PRE}" >> "$GITHUB_OUTPUT"
                 echo "RELEASENAME_POSTFIX=${POSTFIX}" >> "$GITHUB_OUTPUT"
                 RELEASEBODY=$(awk -v RS='Release ' '/'$VERSION':(.*)/ {print $0}' ChangeLog.md)
                 echo "${RELEASEBODY}" > CHANGELOG.md

            
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v.${{ steps.set_env_var.outputs.version }}-${{ steps.set_env_var.outputs.RELEASENAME_POSTFIX }}-${{ github.run_id }}
          release_name: Release ${{ steps.set_env_var.outputs.version }} ${{ steps.set_env_var.outputs.RELEASENAME_POSTFIX }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: ${{ steps.set_env_var.outputs.IS_PRERELEASE }}
              
      - name: Upload Release Assets
        id: upload-release-assets
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          assets_path: ./release

      - name: Upload Changelog artifact
        uses: actions/upload-artifact@main
        with:
          name: CHANGELOG.md
          path: CHANGELOG.md
