name: Build & Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
 build:
   runs-on: ubuntu-latest
   env:
     LIBRARIES: WiFi101 WiFiNINA

   strategy:
     matrix:
       fqbn: [
         '"esp8266:esp8266:huzzah" "https://arduino.esp8266.com/stable/package_esp8266com_index.json"'
       ]

   steps:
     - uses: actions/checkout@v1
       with:
         fetch-depth: 1
     - name: compile-examples for official Arduino boards
       if: startsWith(matrix.fqbn, '"esp8266:esp8266') != true
       uses: arduino/actions/libraries/compile-examples@master
       with:
         fqbn: ${{ matrix.fqbn }}
         libraries: ${{ env.LIBRARIES }}
     - name: compile-examples for ESP8266 boards
       if: startsWith(matrix.fqbn, '"esp8266:esp8266')
       uses: arduino/actions/libraries/compile-examples@master
       with:
         fqbn: ${{ matrix.fqbn }}
         entrypoint: /github/workspace/.github/workflows/install-python-wrapper.sh
